### ISSUE TITLE
Certain players (assumably non-season 1) cause error

### ISSUE THREAD

**Issue by merryt** [notmarkmiranda/poker_season_tracker#19]
https://pokerseason.herokuapp.com/participants/18
https://pokerseason.herokuapp.com/participants/19

https://www.dropbox.com/s/k7lpx6qu16qs1ar/Screenshot%202016-11-18%2009.15.29.png?dl=0

**Comment by notmarkmiranda** [comment]
i think this got fixed with a few other random things
